### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by shinzui** [janestreet/shexp#9] opened 2018-10-10 14:15 UTC
`shexp` does not install on OCaml 4.0.7 with new versions of `Base`.

**Comment by diml** [comment] 2018-10-30 11:40
The version that's released in opam hasn't been tested with 4.07. We are planning to do a new major release of all Jane Street packages in the coming weeks.

**Comment by struktured** [comment] 2019-01-10 23:00
@diml any updated estimate on this upgrade?

**Comment by diml** [comment] 2019-01-14 16:44
Soon hopefully, the release got blocked unexpectedly due to compatibility problems caused by the bigarray module moving to the stdlib, but these issues are almost fixed.

**Comment by xclerc** [comment] 2019-03-11 14:43
Fixed in release v0.12.0.

**Closed by xclerc** 2019-03-11 14:43 UTC
